ボウリング問題の回答を作成
t-koba-dev/ruby-practices pull request #4
Opened 2021-01-19 08:41 UTC by t-koba-dev

[ボウリングのスコア計算プログラム](https://bootcamp.fjord.jp/practices/210)の回答を提出します。

ご確認のほど、よろしくお願いいたします。

2021-01-23 12:04 UTC, torinoko requested changes
コメントしました！
全体的によさそうな感じがしますが、まだすっきりできそうな気がします。
ちょっと考えてみてください〜！

2021-01-23 12:04 UTC, torinoko commented on 04.bowling/bowling.rb
> +  scores[index..-1].each do |i|
`-1` しているのは理由ありますか？
ちょっとパッと見て分からなかったので、教えてもらえると嬉しいです〜

2021-01-23 12:04 UTC, torinoko commented on 04.bowling/bowling.rb
> +             end
`if` の結果を変数に代入する方法は、あまり一般的ではないです。
なので読む側としてはちょっとカロリー使います。
別の形に置き換えられるといいですね。
短い処理なので「三項演算子」を使ってもいいかもしれませんね。

2021-01-23 12:04 UTC, torinoko commented on 04.bowling/bowling.rb
> +               end
ここの `if` も同じですね〜。
ここの複雑さを気にされてたのはとても勘がいいですね！
たとえばこの `if` をまるっとメソッドにしちゃうのはどうでしょう？

2021-01-23 12:04 UTC, torinoko commented on 04.bowling/bowling.rb
> +      frames.push(shots.map { |n| n })
ここの `.map { |n| n }` はどういう意図でいれていますか？

2021-01-23 12:04 UTC, torinoko commented on 04.bowling/bowling.rb
> +        frames.push(shots.map { |n| n })
ここの `.map { |n| n }` も確認お願いします！

2021-01-23 12:29 UTC, t-koba-dev commented on 04.bowling/bowling.rb
> +      frames.push(shots.map { |n| n })
ご指摘ありがとうございます！

こちらの`.map { |n| n }`は必要なかったです💦
`.map { |n| n }`の意図については下記にコメントします🙇‍♂️

2021-01-23 12:42 UTC, t-koba-dev commented on 04.bowling/bowling.rb
> +        frames.push(shots.map { |n| n })
同一オブジェクトshotsへの参照による、値の上書きを避けることを意図しています。

この`push_shos_to_frames`メソッドでは、
1フレームにおける投球ごとに倒したピン数を表す配列shotsを、
1フレームごとに配列framesへ格納するのですが、

`.map { |n| n }`を記述しない場合、
`frames.push(shots)`ではshotsオブジェクトへの参照が格納されるため、
`frames.push(shots)`を実行するたびに、
既にframesに格納した値も変更されてしまいました。

そのため、同一オブジェクト参照による上書きを避けるため、
mapメソッドを使って新しいオブジェクトを都度生成するように対処しました。

2021-01-23 12:55 UTC, t-koba-dev commented on 04.bowling/bowling.rb
> +  scores[index..-1].each do |i|
`scores[index..-1]`は、10フレーム目の各投球で倒したピンの数を表してます。

ゲームによって10フレーム目の投球数が2,3球に変動するので、
どちらの場合でも対応できるように、
10フレーム目の初球`scores[index]`からラスト一球`scores[-1]`を処理するようにしました。

2021-01-23 13:03 UTC, t-koba-dev commented on 04.bowling/bowling.rb
> +             end
ご指摘ありがとうございます！

確かに読みづらいですね...すみません！

以下のように三項演算子に改善します🙇‍♂️
```rb
shots << (i == 'X' ? 10 : i.to_i)
```

2021-01-23 13:19 UTC, t-koba-dev commented on 04.bowling/bowling.rb
> +               end
アドバイスありがとうございます！！

メソッドに置き換える発想はなかったです！🤩
rubocop-fjordも全てパスするようになりました！😆
感動です〜👏

修正コミットとして、
ストライク時のスコア計算処理を、
新しくメソッド(`calculate_when_strike`)に切り出しました！

2021-01-24 01:43 UTC, torinoko commented on 04.bowling/bowling.rb
> +  scores[index..-1].each do |i|
あーなるほど、ありがとうございます！

2021-01-24 01:44 UTC, torinoko commented on 04.bowling/bowling.rb
> +             end
すごく読みやすくなりましたね！ 👍 
（あと謝ることはないですよ〜！書き方きつく感じたらこちらこそごめんなさい！！）

2021-01-24 01:45 UTC, torinoko commented on 04.bowling/bowling.rb
> +               end
いいですね〜！！！
処理にわかりやすい名前がつくので、point 加算するときも読みやすくなりますね！

2021-01-24 01:49 UTC, torinoko commented on 04.bowling/bowling.rb
> +        frames.push(shots.map { |n| n })
なるほど！
確かにオブジェクトの参照になりますね〜。
意図を理解しました！

ただ `#map` だとちょっと意図が伝わりにくい気がします。
オブジェクトを別のものに変えるのであれば `#dup` などどうでしょう？

2021-01-24 01:58 UTC, torinoko approved these changes
よさそうです！
こういうのもありますよ〜というところをコメントしました。
ちょっと調べたり考えたりしてもらえたら嬉しいです！

2021-01-24 01:58 UTC, torinoko commented on 04.bowling/bowling.rb
> +        frames.push(shots.map { |n| n })
なるほど！
確かにオブジェクトの参照になりますね〜。
意図を理解しました！

ただ `#map` だとちょっと意図が伝わりにくい気がします。
オブジェクトを別のものに変えるのであれば `#dup` などどうでしょう？

2021-01-24 01:58 UTC, torinoko commented on 04.bowling/bowling.rb
> +  scores.each_with_index do |s, index|
後出しで申し訳ない、かつ好みの問題なのですが、プログラム内で `index` という変数がずっと使われていますね。
この時点では何を意味しているのかわかるのですが、メソッドに渡し続けているうちに「何の `index` なんだろう？」ってちょっとわからなくなりました。
引数に渡す時点でもいいので、わかりやすい名前が付けられていると読み手により優しいなーと感じました！（今回はこのままでも大丈夫です！）

2021-01-24 02:40 UTC, t-koba-dev commented on 04.bowling/bowling.rb
> +        frames.push(shots.map { |n| n })
アドバイスありがとうございます！

確かに、複製する意図を伝えるにはdupが適切ですね！

`#dup`知らなかったです！
欲しかったメソッドそのものでした笑

Objectクラスにこんな便利なメソッドあったんですね〜！
Objectクラスのドキュメント眺めてみます〜！

こんな便利なメソッド教えてくださり、ありがとうございます！！
感謝！😆

2021-01-24 02:57 UTC, t-koba-dev commented on 04.bowling/bowling.rb
> +  scores.each_with_index do |s, index|
あー！たしかに！
ご指摘いただけて気付けました！ありがとうございます！😌

`index`よりも、ボウリングに関する名前の方が分かりやすいですよね。

とても参考になります！🙏

2021-01-24 04:05 UTC, torinoko approved these changes
👍 👍 👍 

さらに追加ですがアレなのですが（ごめんなさい！）
`number_of_shots_minus1` で `-1` になっていますが、後の方のメソッドで `+1` とか `+2` とかしているので、最初の段階で index に `+1` した値を `number_of_shots` として処理するかもな〜と思いました！
そうすると `..-1` や `+1` の処理が不要になるかなーと。

2021-01-24 04:28 UTC, t-koba-dev commented
> `number_of_shots_minus1` で `-1` になっていますが、後の方のメソッドで `+1` とか `+2` とかしているので、最初の段階で index に `+1` した値を `number_of_shots` として処理するかもな〜と思いました！
> そうすると `..-1` や `+1` の処理が不要になるかなーと。

重ね重ねありがとうございます！

最初に`添字+1`してあげれば、
- 二度手間な処理も無くすことができるし、
- 変数名からminus1が取れて分かりやすくなるし、

一石二鳥ですね！

もう少し考えてみます！
貴重なお時間いただいてレビューいただきありがとうございます！！😊

2021-01-24 05:17 UTC, merged